# ------------------------------------------------------------------------------
# NGINX Ingress
# ------------------------------------------------------------------------------

flows:

  ingress-nginx:
    - task: helm
      in:
        command: upgrade
        chart:
          name: ingress-nginx
          value: "${k8sImport}/04-ingress-nginx/chart"
          values: "${profile}/ingress-nginx/values.yaml"
        envars: ${clusterRequest.envars}

    - "${k8sContext.ingressAnnotation(context, 'kubernetes.io/ingress.class: nginx')}"
