# ------------------------------------------------------------------------------
# NGINX Ingress
# ------------------------------------------------------------------------------

flows:

  ingress-nginx:
  
    - task: kubectl
      in:
        command: create
        namespace:
          name: ingress-nginx
        envars: ${clusterRequest.envars}   

    - task: helm3
      in:
        command: upgrade
        chart:
          name: ingress-nginx
          namespace: ingress-nginx
          value: ingress-nginx/ingress-nginx
          values: "${profile}/ingress-nginx/values.yaml"
        envars: ${clusterRequest.envars}

    - "${k8sContext.ingressAnnotation(context, 'kubernetes.io/ingress.class: nginx')}"
