# ------------------------------------------------------------------------------
# Prometheus
# ------------------------------------------------------------------------------

flows:

  prometheus:


    - task: kubectl
      in:
        command: create
        namespace:
          name: telemetry
        envars: ${clusterRequest.envars}

    - task: helm3
      in:
        command: upgrade
        chart:
          name: prometheus-operator
          version: 8.12.12
          namespace: telemetry
          value: stable/prometheus-operator
          values: "${profile}/prometheus/values.yaml"
        envars: ${clusterRequest.envars}

    # We are letting the rest of the cluster construction process that
    # Prometheus is enabled. Any of chart being installed can look for
    # this feature being set to determine is P8s service monitors
    # should be installed.
    
    - ${k8sContext.enableFeature('prometheus')}