apiVersion: v1
name: metacontroller
version: 0.0.1
appVersion: 0.4.0
home: https://metacontroller.app
description: Metacontroller is an add-on for Kubernetes that makes it easy to write and deploy custom controllers. Although the open-source project was started at Google, the add-on works the same in any Kubernetes cluster.
