# ------------------------------------------------------------------------------
# NGINX Ingress
# ------------------------------------------------------------------------------

flows:

  ingress-nginx-legacy:

    - task: kubectl
      in:
        command: create
        namespace:
          name: ingress-nginx
        envars: ${clusterRequest.envars}

    - task: helm3
      in:
        command: upgrade
        chart:
          name: ingress-nginx
          namespace: ingress-nginx
          value: "${k8sImport}/04-ingress-nginx-legacy/chart"
          values: "${profile}/ingress-nginx-legacy/values.yaml"
        envars: ${clusterRequest.envars}

    - "${k8sContext.ingressAnnotation(context, 'kubernetes.io/ingress.class: nginx')}"
