kind: Service
apiVersion: v1
metadata:
  name: nginx-ingress-metrics-service
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name:  nginx-ingress-metrics-service
    app.kubernetes.io/part-of: ingress-nginx
spec:
  ports:
    - name: metrics
      port: 10254
      targetPort: metrics
  selector:
    app.kubernetes.io/name:  ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx