master:
  hostNetworking: true
  jenkinsUrlProtocol: "https"
  ingress:
    enabled: true
    apiVersion: "extensions/v1beta1"
    annotations: ${k8sContext.ingressAnnotations(context,6)}
    hostName: jenkins.${domain}
    tls:
      - hosts:
        - jenkins.${domain}
        secretName: jenkins-tls
  adminUser: ${secrets.adminUsername}
  adminPassword: ${secrets.adminPassword}
  installPlugins:
    - configuration-as-code:1.35
    - bouncycastle-api:2.17
    - kubernetes:1.22.3
    - workflow-job:2.36
    - workflow-aggregator:2.6
    - credentials-binding:1.20
    - git:4.0.0
    - github-branch-source:2.5.8
    - blueocean:1.17.0
    - saml:1.1.4

  enableXmlConfig: false

  JCasC:
    enabled: true
    defaultConfig: true
    pluginVersion: "1.35"
    supportPluginVersion: "1.35"
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.
