kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-dns-autoscaler
  namespace: kube-system
data:
  linear: |-
    {
      "coresPerReplica": {{ .Values.cpa.scaling.coresPerReplica }},
      "nodesPerReplica": {{ .Values.cpa.scaling.nodesPerReplica }},
      "min": {{ .Values.cpa.scaling.min }},
      "preventSinglePointFailure": true
    }