{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "fluent-bit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fluent-bit.fullname" . }}
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
    verbs: ["get", "list", "watch"]
{{- if .Values.rbac.pspEnabled }}
  - apiGroups:
    - {{ template "rbac.pspApiGroup" . }}
    resources:
    - podsecuritypolicies
    resourceNames:
    - {{ template "fluent-bit.fullname" . }}
    verbs:
    - use
{{- end }}
{{- end -}}