apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "fluent-bit.fullname" . }}
  labels:
    app: {{ template "fluent-bit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
       app: {{ template "fluent-bit.name" . }}
       release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "fluent-bit.name" . }}
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      serviceAccountName: {{ template "fluent-bit.name" . }}
      containers:
      - name: fluent-bit
        image:  "{{ .Values.image.fluent_bit.repository }}:{{ .Values.image.fluent_bit.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
          - containerPort: 2020
        command:
          - /fluent-bit/bin/fluent-bit
          - -c
          - /fluent-bit/etc/fluent-bit.conf
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc
        - name: certs 
          mountPath: /fluent-bit/crt/
          readOnly: true
        - name: pems 
          mountPath: /fluent-bit/key/
          readOnly: true
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      
      terminationGracePeriodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: {{ template "fluent-bit.name" . }}-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: certs
        secret:
          secretName: fluentbit-certs
      - name: pems
        secret:
          secretName: fluentbit-pems