apiVersion: v1
kind: Secret
metadata:
  name: fluentbit-pems
  labels:
    app: {{ template "fluent-bit.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  "server.key": |-
    {{  .Values.backend.forward.fluent_pem | b64enc }}
