apiVersion: v1
name: ingress-nginx
version: 1.27.0
appVersion: 0.27.0
home: https://github.com/kubernetes/ingress-nginx
description: An nginx Ingress controller that uses ConfigMap to store the nginx configuration.